  [[main]]
  name = "Trang Chủ"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Blog"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Giới Thiệu"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Giấy Chứng Nhận"
  weight = 500
  identifier = "accomplishments"

  [[main]]
  name = "Awards"
  weight = 510
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments"  


  [[main]]
  name = "Thông tin liên lạc"
  weight = 600
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"